backend:
  name: github
  repo: otmicka23/poc-gatsby-netlifyCms
media_folder: content/assets
public_folder: /assets
collections:
  - name: blog
    label: Blog
    folder: /content/blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: description, label: description }
      - { name: html, label: Body, widget: markdown }
