backend:
  name: github
  repo: tmicka23/poc-gatsby-netlifyCms
  branch: master
  site_domain: netlify.app
  base_url: https://api.netlify.com
  auth_endpoint: auth
  api_root: https://api.github.com
media_folder: content/assets
public_folder: /assets
collections:
  - name: blog
    label: Blog
    folder: /content/blog/
    create: true
    fields:
      - { name: title, label: Title }
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: datetime }
      - { name: description, label: description }
      - { name: body, label: Body, widget: markdown }
